# Config file
Debug: true

# App
App:
  Name: "hertz-permission"
  User:
    Super: ["super_user", "sys_admin"]
    Password:
      Salt: "hertz-permission" # use to encode
      Init: "Admin123!" # default password

# Server config
Server: 
  Http:
    Addr: "127.0.0.1:8080"
  Client:
  Rpc:

# Log config
Log:
  Dir: "./logs/"
  MaxSize: 1     # A file can be up to 20M.
  MaxBackups: 5   # Save up to 5 files at the same time.
  MaxAge: 30      # A file can exist for a maximum of 10 days.
  Compress: false  # Compress with gzip.

# Database config
Database:
  Driver: "mysql"  # mysql || postgresql || postgres
  Host: "smileiot.tpddns.cn" # local:192.168.0.100
  Port: 13306 # local:3306
  Username: "root"
  Password: "asdf1234"
  Dbname: "common"

# Redis config
Redis:
  Network: "tcp"
  Addr: "127.0.0.1:6379"
  Password:
  DB: 0
  Size: 100

  # Session
Session:
  Driver: "redis" # redis || cookie
  Name: "hertz-permission"
  Secret: "secret"

# Swagger config
Swagger:
  Version: 1.0.0
  Host: "127.0.0.1:8080"
  BasePath: "/"
  Schemes: ["http"]
  Title: "go-common"
