# Config file
Debug: true

# App
App:
  Name: "hertz-permission"
  User:
    Super: ["super_user", "sys_admin"]
    Password:
      Salt: "hertz-permission" # use to encode
      Init: "Admin123!" # default password

# Server config
Server: 
  Http:
    Addr: ":8080"
  Client:
  Rpc:

# Log config
Log:
  Dir: "./logs/"

# Database config
Database:
  Driver: "mysql"  # mysql || postgresql || postgres
  Host: "192.168.0.100"
  Port: 3306
  Username: "root"
  Password: "asdf1234"
  Dbname: "common"

# Redis config
Redis:
  Network: "tcp"
  Addr: ":6379"
  Password:
  Size: 10

# Session
Session:
  Driver: "redis" # redis || cookie
  Name: "hertz-permission"
  Secret: "secret"


# Swagger config
Swagger:
  Host: ":8080"