basePath: /
definitions:
  model.PermissionOption:
    properties:
      alias:
        type: string
      child:
        items:
          $ref: '#/definitions/model.PermissionOption'
        type: array
      id:
        type: integer
      name:
        type: string
      show:
        type: string
    type: object
  model.PermissionShow:
    properties:
      alias:
        type: string
      components:
        type: string
      create_at:
        type: string
      icon:
        type: string
      id:
        type: integer
      key:
        type: string
      name:
        type: string
      pid:
        type: integer
      remark:
        type: string
      sort:
        type: integer
      status:
        type: integer
      type:
        type: string
      update_at:
        type: string
      update_by:
        type: string
      update_time:
        type: string
      visible:
        type: integer
    type: object
  model.RoleOption:
    properties:
      id:
        type: integer
      key:
        type: string
      name:
        type: string
    type: object
  model.RoleShow:
    properties:
      create_at:
        type: string
      creator_id:
        type: integer
      id:
        type: integer
      is_del:
        type: string
      key:
        type: string
      name:
        type: string
      remark:
        type: string
      status:
        type: integer
      update_at:
        type: string
      update_by:
        type: string
      update_time:
        type: string
    type: object
  permission.RespInfo:
    properties:
      alias:
        type: string
      components:
        type: string
      create_at:
        type: string
      icon:
        type: string
      id:
        type: integer
      key:
        type: string
      name:
        type: string
      pid:
        type: integer
      remark:
        type: string
      sort:
        type: integer
      status:
        type: integer
      type:
        type: string
      update_at:
        type: string
      update_by:
        type: string
      update_time:
        type: string
      visible:
        type: integer
    type: object
  permission.RespList:
    properties:
      etime:
        type: string
      limit:
        type: integer
      offset:
        type: integer
      permissions:
        items:
          $ref: '#/definitions/model.PermissionShow'
        type: array
      stime:
        type: string
      total:
        type: integer
    type: object
  response.BaseResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  role.RespInfo:
    properties:
      create_at:
        type: string
      creator_id:
        type: integer
      id:
        type: integer
      is_del:
        type: string
      key:
        type: string
      name:
        type: string
      remark:
        type: string
      status:
        type: integer
      update_at:
        type: string
      update_by:
        type: string
      update_time:
        type: string
    type: object
  role.RespList:
    properties:
      etime:
        type: string
      limit:
        type: integer
      offset:
        type: integer
      roles:
        items:
          $ref: '#/definitions/model.RoleShow'
        type: array
      stime:
        type: string
      total:
        type: integer
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  title: hertz-permission
  version: 1.0.0
paths:
  /api/permission/{id}/del:
    delete:
      consumes:
      - application/json
      description: This is a api to del permission
      parameters:
      - description: 权限ID
        example: 1
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 删除权限
      tags:
      - PermissionDel
  /api/permission/{id}/edit:
    put:
      consumes:
      - application/json
      description: This is a api to edit permission
      parameters:
      - description: 权限ID
        example: 1
        in: query
        name: id
        required: true
        type: integer
      - description: 父级ID
        example: 1
        in: body
        name: pid
        required: true
        schema:
          type: integer
      - description: 权限名称
        example: '"permission.add"'
        in: body
        maxLength: 32
        name: name
        required: true
        schema:
          type: string
      - description: 别名
        example: '"添加权限"'
        in: body
        maxLength: 32
        name: alias
        required: true
        schema:
          type: string
      - description: 权限类型[D:目录;M:菜单;B:按钮]
        enum:
        - '"D"'
        - '"M"'
        - '"B"'
        in: body
        name: type
        required: true
        schema:
          type: string
      - description: 权限全局标识[即路由，类型为目录可空]
        in: body
        maxLength: 32
        name: key
        schema:
          type: string
      - description: 前端页面路径[类型为按钮可空]
        in: body
        maxLength: 32
        name: components
        schema:
          type: string
      - default: 0
        description: 排序[从小到大]
        in: body
        name: sort
        schema:
          type: integer
      - description: 图标
        in: body
        maxLength: 255
        name: icon
        schema:
          type: string
      - description: 菜单状态[1:显示;0:隐藏]
        enum:
        - 1
        - 0
        in: body
        name: visible
        schema:
          type: integer
      - description: 菜单状态[1:显示;0:隐藏]
        enum:
        - 1
        - 0
        in: body
        name: status
        schema:
          type: integer
      - description: 备注
        in: body
        maxLength: 255
        name: remark
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 修改权限
      tags:
      - PermissionEdit
  /api/permission/{id}/info:
    get:
      consumes:
      - application/json
      description: This is a api of permission info
      parameters:
      - description: 权限ID
        example: 1
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/permission.RespInfo'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 权限详情
      tags:
      - PermissionInfo
  /api/permission/add:
    post:
      consumes:
      - application/json
      description: This is a api to add permission
      parameters:
      - default: 0
        description: 父级ID
        in: body
        maximum: 10
        name: pid
        required: true
        schema:
          type: integer
      - description: 权限名称
        example: '"permission.add"'
        in: body
        maxLength: 32
        name: name
        required: true
        schema:
          type: string
      - description: 别名
        example: '"添加权限"'
        in: body
        maxLength: 32
        name: alias
        required: true
        schema:
          type: string
      - description: 权限类型[D:目录;M:菜单;B:按钮]
        enum:
        - '"D"'
        - '"M"'
        - '"B"'
        in: body
        name: type
        required: true
        schema:
          type: string
      - description: 权限全局标识[即后端路由，类型为目录可空]
        in: body
        maxLength: 32
        name: key
        schema:
          type: string
      - description: 前端页面路径[类型为按钮可空]
        in: body
        maxLength: 32
        name: components
        schema:
          type: string
      - default: 0
        description: 排序[从小到大]
        in: body
        name: sort
        schema:
          type: integer
      - description: 图标
        in: body
        maxLength: 255
        name: icon
        schema:
          type: string
      - description: 菜单状态[1:显示;0:隐藏]
        enum:
        - 1
        - 0
        in: body
        name: visible
        schema:
          type: integer
      - description: 菜单状态[1:显示;0:隐藏]
        enum:
        - 1
        - 0
        in: body
        name: status
        schema:
          type: integer
      - description: 备注
        in: body
        maxLength: 255
        name: remark
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 添加权限
      tags:
      - PermissionAdd
  /api/permission/list:
    get:
      consumes:
      - application/json
      description: This is a api of permission list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/permission.RespList'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 权限列表
      tags:
      - PermissionList
  /api/permission/option:
    get:
      consumes:
      - application/json
      description: This is a api of permission option
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.PermissionOption'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 权限下拉选项
      tags:
      - PermissionOption
  /api/permission/route:
    get:
      consumes:
      - application/json
      description: This is a api of route option
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  items:
                    type: string
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 路由下拉选项
      tags:
      - PermissionRouteOption
  /api/role/{id}/del:
    delete:
      consumes:
      - application/json
      description: This is a api to add role
      parameters:
      - description: 角色ID
        example: 1
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 删除角色
      tags:
      - RoleDel
  /api/role/{id}/edit:
    put:
      consumes:
      - application/json
      description: This is a api to edit role
      parameters:
      - description: 角色ID
        example: 1
        in: query
        name: id
        required: true
        type: integer
      - description: 角色名
        example: “系统管理员”
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: 角色标识
        example: “SYS_ADMIN”
        in: body
        name: Key
        required: true
        schema:
          type: string
      - description: 角色状态[1:正常;0:停用]
        enum:
        - 1
        - 0
        in: body
        name: status
        schema:
          type: integer
      - description: 备注
        in: body
        maxLength: 255
        name: remark
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 编辑角色
      tags:
      - RoleEdit
  /api/role/{id}/info:
    get:
      consumes:
      - application/json
      description: This is a api of role info
      parameters:
      - description: 角色ID
        example: 1
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/role.RespInfo'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 角色详情
      tags:
      - RoleInfo
  /api/role/add:
    post:
      consumes:
      - application/json
      description: This is a api to add role
      parameters:
      - description: 角色名
        example: “系统管理员”
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: 角色标识
        example: “SYS_ADMIN”
        in: body
        name: Key
        required: true
        schema:
          type: string
      - description: 角色状态[1:正常;0:停用]
        enum:
        - 1
        - 0
        in: body
        name: status
        schema:
          type: integer
      - description: 备注
        in: body
        maxLength: 255
        name: remark
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 添加角色
      tags:
      - RoleAdd
  /api/role/list:
    get:
      consumes:
      - application/json
      description: This is a api of role list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/role.RespList'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 角色列表
      tags:
      - RoleList
  /api/role/option:
    get:
      consumes:
      - application/json
      description: This is a api of role option
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.RoleOption'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 角色下拉选项
      tags:
      - RoleOption
  /api/user/{id}/assign:
    post:
      consumes:
      - application/json
      description: This is a api to assign role for user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: 角色分配
      tags:
      - UserRoleAssign
schemes:
- http
swagger: "2.0"
